# step 1 import
# agent.py
import os
import sys
from pathlib import Path
import datetime
from dotenv import load_dotenv
from google.adk.agents import Agent,LoopAgent
from google.adk.tools import agent_tool

load_dotenv()
MODEL = os.getenv("MODEL", "gemini-flash-latest")

# ————————SUB-AGENT PLANNER————————————————————————————————————————————————————————————————
blog_planner = Agent(
    name="blog_planner",
    model=MODEL,
    description="This agent is responsible for planning the blog post. It will take the topic and generate a detailed outline in Markdown format, including headings, subheadings, and key points to cover.",
    instruction="""
    You are a blog post planner. Your task is to create a detailed outline for a blog post based on the given topic. The outline should be structured in Markdown format, with clear headings and subheadings. Each section should include key points that will be covered in the blog post. Ensure that the outline is comprehensive and provides a clear roadmap for writing the blog post.
    The format should be as follows:
    # Blog Post Title  
    ## short intro
    ## 4-6 main sections with headings and subheadings(each with 2-3 bullet points) Avoid generic bullet points like 'Introduction to the topic' or 'Key point 1'. Each bullet point must contain concrete ideas related to the specific topic
    ## conclusion

    If there is code, weave in specific examples and code snippets to illustrate the points being made. The outline should be clear, concise, and easy to follow, providing a solid foundation for writing the full blog post.
    Return the outline in Markdown format only, without any additional commentary or explanation.
    """,
        output_key="blog-outline",
)

class OutlineValidationChecker(Agent):
    def __init__(self):
        super().__init__(
            name="OutlineValidationChecker", 
            model=MODEL, 
            description="Validates if the structure and content of blog post outlines is available", 
            instruction="""Check the outline in state`blog_outline`.Whether the outline has a title,intro,4-6sections,
            and a conclusion,respond exactly "OK",otherwise respond exactly "Retry" and list missing pieces.
            """,
            output_key="validation_result")


robust_blog_planner = LoopAgent(
    name="robust_blog_planner",
    description="Retries planning if validation fails.",
    sub_agents=[blog_planner, OutlineValidationChecker()],
    max_iterations=3,
)

#———————Sub-agent: Writer————————————————————————————————————————————————————————————————
blog_writer = Agent(
    name="BlogWriter",
    model=MODEL,
    description="Writes a blog post based on the provided outline. It will take the outline generated by the blog_planner and expand it into a full blog post, ensuring that the content is engaging, informative, and well-structured.",
    instruction="""
Write a complete Markdown article based on the provided outline in `blog_outline`.
Guidelines:
- Audience:software engineers; skip basicsand focus on practical insights.
- Explain both the 'how' and 'why' behind each point in the outline.
- Include concise code snippets when helpful to illustrate key points.
- Follow the outline's structure (H2/H3).
- Output should be in Markdown format only, without any additional commentary or explanation, no fence around the article.
""",
output_key="blog_post",
)

class BlogPostValidationChecker(Agent):
    def __init__(self):
        super().__init__(
            name="BlogPostValidationChecker", 
            model=MODEL, 
            description="Validates the final blog post.", 
            instruction="""Check the `blog_post` for:intro,clear sections matching the outline,conclusion,and technical clarity. 
            If passes,respond exactly "OK". If fails, respond exactly "Retry" with the specific fixes.
            """,
            output_key="validation_result")
        
robust_blog_writer = LoopAgent(
    name="robust_blog_writer",
    description="Retries writing if validation fails.",
    sub_agents=[blog_writer, BlogPostValidationChecker()],
    max_iterations=3,
)        

# Expose planner/writer agents as tools for external use, so the root agent can call them as needed.

planner_tool = agent_tool.AgentTool(agent = robust_blog_planner)
writer_tool = agent_tool.AgentTool(agent = robust_blog_writer)

#———————Root-agent: Trends-Plan-Write————————————————————————————————————————————————————————————————
root_agent = Agent(
    name="Blogger",
    model=MODEL,
    description="Minimal multi-agent system for planning and writing blog posts.",
    instruction=f"""
If the user gives a topic:
1) Call the planner_tool to generate a detailed outline for the blog post.
2) Call the writer_tool to write a complete blog post based on the outline.
3) End with 3 alternative titles and 2 tweet-length hooks.

If the trends tool fails or times out continue with a sensible outline and draft anyway.

Date:{datetime.datetime.now().strftime("%Y-%m-%d")}
""",
tools=[planner_tool, writer_tool],
)


